databaseChangeLog:
  -  changeSet:
       id: create-table-user-table
       author: alvaro-longueira
       changes:
         -  createTable:
              tableName: user_table
              columns:
                -  column:
                     name: id
                     type: varchar(255)
                     constraints:
                       primaryKey: true
                       nullable: false
                - column:
                    name: first_name
                    type: varchar(255)
                - column:
                    name: last_name
                    type: varchar(255)
                - column:
                    name: nickname
                    type: varchar(255)
                - column:
                    name: password
                    type: varchar(255)
                - column:
                    name: email
                    type: varchar(255)
                - column:
                    name: country
                    type: varchar(255)
                - column:
                    name: created_at
                    type: timestamp
                    constraints:
                      nullable: false
                - column:
                    name: updated_at
                    type: timestamp
                - column:
                    name: version
                    type: bigint