server:
  port: ${APP_SERVER_PORT:8080}
  shutdown: graceful
  error:
    include-message: always

# SPRING CONFIG
spring:
  application:
    name: user-service
    version: '@project.version@'
  profiles:
    active: ${APP_ACTIVE_PROFILE:dev}
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

# MANAGEMENT ENDPOINTS
management:
  security:
    enabled: false
  context-path: /
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  health:
    binders:
      enabled: true
    db:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# OPENAPI GENERATION
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
